### ISSUE TITLE
chore: forgify deployment scripts

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#105]

**Comment by fedgiac** [comment]
To keep deterministic deployments we need to replay the existing transactions since it would be really hard to make Foundry recompute the same bytecode metadata (for example because of remappings).
We'd also need to come up with a custom contract verification procedure, which probably needs another isssue.

**Comment by mfw78** [comment]
With the path being for contract legacy deployment to be to revert to the legacy tag, this issue is now redundant.
