### ISSUE TITLE
tests(core): `GPv2TradeSimulator`

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#122]

**Comment by yomanthunder** [comment]
Hey @mfw78 i would like to contribute to the issue , could you please provide contribution guidelines

**Comment by fedgiac** [comment]
Hello yomanthunder and thanks for your interest! mfw78 already started working on this. In the end, we were considering getting rid of the contract `GPv2TradeSimulator` in the first place rather than migrating the tests.

We don't have formal contribution guidelines but we're considering introducing them. If you have some specific ideas on what you want to see on them, please comment in the [dedicated issue](https://github.com/cowprotocol/contracts/issues/205).
