### ISSUE TITLE
tests(e2e): `zero-ex v2`

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#132]
May be implemented as a fork test.

**Comment by meetmangukiya** [comment]
Since we plan to remove node_modules for artifacts, there are two options here:
1. Copy over the artifacts needed to deploy 0x v2 in the test directory
2. Remove the tests altogether because the protocol is too old and even documentation and deployment addresses are not available in the current 0x docs

What should we do @fedgiac @mfw78 ?

**Comment by mfw78** [comment]
Yep, I'd be a fan of just binning it.

**Comment by meetmangukiya** [comment]
I couldn't find anything in their news blog, might be too old, maybe there was no blog post about it, but they integrated v4 of their contracts and went live on March 1st, 2021 https://0x.org/post/0x-api-swap-now-supports-0x-protocol-v4

**Comment by mfw78** [comment]
Please submit a PR removing zeroex.

**Comment by meetmangukiya** [comment]
It's in the same pr that is currently linked to this issue

**Comment by mfw78** [comment]
Closed by #219
