### ISSUE TITLE
smart contracts attacked 

### ISSUE THREAD

**Issue by chebii2** [cowprotocol/contracts#35]

**Comment by nlordell** [comment]
Can you please provide more context? In what way was the smart contract attacked?

Also, doing some quick investigation I can't find any evidence of this. Do you mind sharing it?

**Comment by fedgiac** [comment]
User chebii2 (OP) appears to be creating unsubstantiated posts across this repository since last month (maybe automatically generated?).

So far we replied to each request without receiving actionable information.

However, this new issue is a serious allegation that must be backed by supporting evidence.

Please provide supporting evidence for this claim. If no supporting evidence of a security issue reaches us in one week from now (until 2023-01-10), this account will be barred from making contributions to the CoW Swap organization and the issue will be closed.

Note that there is a bug bounty that pays for issues that were found in our smart contracts, you can find more details [here](https://medium.com/@gnosisPM/announcing-gnosis-protocol-v2-bug-bounty-f3e44e934566). (There is an email to report issues in the post, but if you prefer a more institutionalized approach you can use [Immunefi](https://immunefi.com/bounty/cowprotocol/) to report an issue.)

Example messages by chebii2: [1](https://github.com/cowprotocol/contracts/issues/1#issuecomment-1304718688), [2](https://github.com/cowprotocol/contracts/commit/72623a0429d56d37a7a40791e98a2b7ac5ca7818#commitcomment-94771289), [3](https://github.com/cowprotocol/contracts/issues/29#issuecomment-1368652170).

On repos outside the CoW Swap organization: [1](https://github.com/ethereum/go-ethereum/pull/26189#issuecomment-1321311257), [2](https://github.com/bitpay/bitcore/issues/3393).

<details><summary>Screenshot of messages mentioned above.</summary>

![image](https://user-images.githubusercontent.com/58218759/210335786-4d24b751-7c0e-4fa3-8d4b-04bf73f05bf3.png)
![image](https://user-images.githubusercontent.com/58218759/210335950-07f08c05-d15a-4ce9-b390-97dd4fb2a2f9.png)
![image](https://user-images.githubusercontent.com/58218759/210336016-98b30288-892a-4960-93b9-106ad38e62b9.png)
![image](https://user-images.githubusercontent.com/58218759/210336102-a3c21ab8-f9f3-4ca5-8cc7-90838133a161.png)
![image](https://user-images.githubusercontent.com/58218759/210336166-6d40441a-e574-40d3-98e0-d39d6a4f49d9.png)
![image](https://user-images.githubusercontent.com/58218759/210336226-d113e043-fddb-49c5-8efc-6b781a6b3d55.png)

</details>

**Comment by nlordell** [comment]
I'm sorry @chebii2, but you have provided a lot of unsupported claims, that seem related to stolen funds from a wallet and in no way related to CoW Protocol or CoW Swap.

As per [this comment](https://github.com/cowprotocol/contracts/issues/35#issuecomment-1369588764), we will be blocking your account from contributions to the `cowprotocol` org.
